name = "deepseek-gateway"
main = "src/index.tsx"
compatibility_date = "2025-01-01"
minify = true

[[kv_namespaces]]
binding = "AIGATEWAY"
id = "0f61dd04585a456bae5b1c74b297b674"
preview_id = "17a7eb8b1c814b50922f20c29f77a16b"

[vars]
DEEPSEEK_BASE_URL = "https://api.deepseek.com"
